stages:
  - test
  - sonar

test:
  before_script:
    - apt-get update && apt-get install -y git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
  script:
    - export XDEBUG_MODE=coverage
    - ./vendor/bin/phpunit --coverage-clover build/coverage.xml
  artifacts:
    paths:
      - build/coverage.xml

sonar-scanner:
  stage: sonar
  script:
    - sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.sources=src -Dsonar.php.coverage.reportPaths=build/coverage.xml