stages:
  - test
  - sonar

test:
  stage: test
  image: php:8
  before_script:
    - apt-get update && apt-get install -y git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
  script:
    - $env:XDEBUG_MODE = "coverage"
    - vendor\bin\phpunit --coverage-clover coverage.xml --log-junit tests.xml
  artifacts:
    paths:
      - coverage.xml
      - tests.xml

sonar:
  stage: sonar
  image: sonarsource/sonar-scanner-cli
  script:
    - sonar-scanner